COPY INTO REFINITIV.STAGING.LONG_DESCRIPTION_XML FROM @REFINITIV.STAGING.Stage_LongDesc on_error = 'Continue';

CREATE OR REPLACE VIEW REFINITIV.STAGING.V_LONG_DESCRIPTION_STAGING AS
SELECT REPNO AS "RepNo",
    COMPANYNAME AS "CompanyName",
    IRSNO AS "IRSNo",
    CIKNO AS "CIKNo",
    ORGANIZATIONPERMID AS"OrganizationPermID",
    GET(Text.value,'$')::STRING AS "Text",
    CURRENT_TIMESTAMP AS "DataWarehouseInsertTime"
FROM (SELECT *
    FROM (SELECT xml,
            GET(CoIDs.value,'@Type')::STRING AS "Name",
            GET(CoIDs.value,'$')::STRING AS "Value"
        FROM REFINITIV.STAGING.LONG_DESCRIPTION_XML,
        LATERAL FLATTEN(GET(xml,'$'), RECURSIVE => TRUE) CoIDs
        WHERE GET(CoIDs.value, '@') = 'CoID')
        PIVOT(MAX("Value") FOR "Name" IN ('RepNo', 'CompanyName', 'IRSNo', 'CIKNo','OrganizationPermID')) AS p (xml,REPNO,COMPANYNAME,IRSNO,CIKNO,ORGANIZATIONPERMID)),
        LATERAL FLATTEN(GET(xml,'$'), RECURSIVE => TRUE) Text
        WHERE GET(Text.value, '@') = 'Text';

INSERT INTO REFINITIV.PUBLIC.LONG_DESC
    SELECT * FROM REFINITIV.STAGING.V_LONG_DESCRIPTION_STAGING;