CREATE TABLE REFINITIV.STAGING.OFFICERS_AND_DIRECTORS_TENURE_DATES
AS
SELECT
 "RepNo"
,"OrganizationPermID"
,"CompanyName"
,"Production"
,"OfficerPermID"
,"Active"
,"Status"
,"Rank"
,"ID"
,"PersonID"
,"PersonPermID"
,"PersonActive"
,"OfficerStartDay"
,"OfficerStartMonth"
,"OfficerStartYear"
,"OfficerEndDay"
,"OfficerEndMonth"
,"OfficerEndYear"
,"DirectorStartDay"
,"DirectorStartMonth"
,"DirectorStartYear"
,"DirectorEndDay"
,"DirectorEndMonth"
,"DirectorEndYear"
, current_timestamp  AS "DataWareHouseInsertTime"
FROM (
SELECT
  GET(XMLGET(XML,'RepNo'),'$')::STRING AS "RepNo"
 ,GET(XMLGET(XML,'OrganizationPermID'),'$')::STRING AS "OrganizationPermID"
 ,GET(XMLGET(XML,'CompanyName'),'$')::STRING AS "CompanyName"
 ,GET(XMLGET(XML,'Production'),'@Date')::DATETIME AS "Production"
 ,GET(Officer.value,'@OfficerPermID')::STRING AS "OfficerPermID"
 ,GET(Officer.value,'@Active')::STRING AS "Active"
 ,GET(Officer.value,'@Status')::STRING AS "Status"
 ,GET(Officer.value,'@Rank')::STRING AS "Rank"
 ,GET(Officer.value,'@ID')::STRING AS "ID"
 ,regexp_count(officer.path,'\\.|\\[') +1 as l
 ,GET(XMLGET(Officer.value,'Person'),'@ID')::STRING AS "PersonID"
 ,GET(XMLGET(Officer.value,'Person'),'@PersonPermID')::STRING AS "PersonPermID"
 ,GET(XMLGET(Officer.value,'Person'),'@Active')::STRING AS "PersonActive"
 ,GET(XMLGET(XMLGET(XMLGET(Officer.value,'PositionInformation'),'TenureDates'),'OfficerStart'),'@Day')::STRING AS "OfficerStartDay"
 ,GET(XMLGET(XMLGET(XMLGET(Officer.value,'PositionInformation'),'TenureDates'),'OfficerStart'),'@Month')::STRING AS "OfficerStartMonth"
 ,GET(XMLGET(XMLGET(XMLGET(Officer.value,'PositionInformation'),'TenureDates'),'OfficerStart'),'@Year')::STRING AS "OfficerStartYear"
 ,GET(XMLGET(XMLGET(XMLGET(Officer.value,'PositionInformation'),'TenureDates'),'OfficerEnd'),'@Day')::STRING AS "OfficerEndDay"
 ,GET(XMLGET(XMLGET(XMLGET(Officer.value,'PositionInformation'),'TenureDates'),'OfficerEnd'),'@Month')::STRING AS "OfficerEndMonth"
 ,GET(XMLGET(XMLGET(XMLGET(Officer.value,'PositionInformation'),'TenureDates'),'OfficerEnd'),'@Year')::STRING AS "OfficerEndYear"
 ,GET(XMLGET(XMLGET(XMLGET(Officer.value,'PositionInformation'),'TenureDates'),'DirectorStart'),'@Day')::STRING AS "DirectorStartDay"
 ,GET(XMLGET(XMLGET(XMLGET(Officer.value,'PositionInformation'),'TenureDates'),'DirectorStart'),'@Month')::STRING AS "DirectorStartMonth"
 ,GET(XMLGET(XMLGET(XMLGET(Officer.value,'PositionInformation'),'TenureDates'),'DirectorStart'),'@Year')::STRING AS "DirectorStartYear"
 ,GET(XMLGET(XMLGET(XMLGET(Officer.value,'PositionInformation'),'TenureDates'),'DirectorEnd'),'@Day')::STRING AS "DirectorEndDay"
 ,GET(XMLGET(XMLGET(XMLGET(Officer.value,'PositionInformation'),'TenureDates'),'DirectorEnd'),'@Month')::STRING AS "DirectorEndMonth"
 ,GET(XMLGET(XMLGET(XMLGET(Officer.value,'PositionInformation'),'TenureDates'),'DirectorEnd'),'@Year')::STRING AS "DirectorEndYear"
FROM REFINITIV.STAGING.OFFICERS_AND_DIRECTORS_XML
    ,LATERAL FLATTEN (input => XML, recursive => true) as Officer  
WHERE GET(officer.value,'@') = 'Officer' AND (L=4 OR L=5));
